# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  paths:
    include:
    - src/Website/Template.API/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Website/Template.API/**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/Website/Template.API/**/*.csproj'
    arguments: '--collect "Code coverage"'
    testRunTitle: 'Test run'