# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: "Installing NuGet Tool"

- task: NuGetCommand@2
  displayName: "NuGet Restore"
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: "Running Build"
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'src/Website/Template.API/**/*.csproj'

- powershell: |
    $xml = [Xml] (Get-Content src\Website\Template.API\Template.WebApiTemplate.WebApi.csproj.csproj)
    $version = $xml.Project.PropertyGroup.Version
    
    echo $version
    echo $(System.DefaultWorkingDirectory)

    echo "##vso[build.updatebuildnumber]$version"
    echo "##vso[task.setvariable variable=version]$version"
  displayName: 'Get csproj version and set build number'

- task: DotNetCoreCLI@2
  displayName: "Running Unit Tests"
  inputs:
    command: 'test'
    projects: 'src/Website/Template.API/**/*Tests.csproj'
    arguments: '--collect "Code coverage"'

#- task: DotNetCoreCLI@2
#  displayName: "Pushing to NuGet Feed"
#  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#  inputs:
#    command: 'push'
#    packagesToPush: '$(System.DefaultWorkingDirectory)/**/$(buildConfiguration)/**/*.$(version).nupkg'
#    nuGetFeedType: 'internal'
#    publishVstsFeed: 'e7902e1c-f9a4-4aac-9ebb-dcc718fe7809'