# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  paths:
    include:
    - src/client/*

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod --aot
  workingDirectory: src/client
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)/src/client/dist/template-website/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'sa-east-1'
    bucketName: 'template-webapi'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    globExpressions: '**'
    filesAcl: 'public-read'
